'use strict';
const assert = require('node:assert/strict');
const { fresh, validate, summary, countLetters, pagePart } = require('../reading-journal.js');
const date='2026-09-12'; let seq=0;
const entry=(parts,cycle=1)=>({id:String(++seq),date,cycle,source:'paper',parts});
const full=page=>({page,full:true,total:0,keys:[],letters:null});
let b=fresh(); b.entries.push(entry([full(1)]),entry([full(1)]));
assert.equal(summary(b,date).current,1); assert.equal(summary(b,date).volume,2);
b.entries=[entry(Array.from({length:604},(_,i)=>full(i+1)))];
assert.equal(summary(b,date).lifetime,1); b.past=3;
assert.equal(summary(b,date).lifetime,4); b.cycle=2;
assert.equal(summary(b,date).current,0); assert.equal(summary(b,date).lifetime,4);
b.entries.push(entry([full(1)],2)); assert.equal(summary(b,date).current,1);
b.entries.pop(); assert.equal(summary(b,date).current,0);
b=fresh(); const part={page:1,full:false,total:4,keys:['1:1:1','1:1:2'],letters:6};
b.entries.push(entry([part]),entry([part]));
assert.equal(summary(b,date).current,.5); assert.equal(summary(b,date).volume,1); assert.equal(summary(b,date).letters,12);
b.entries.push(entry([{...part,keys:['1:1:3','1:1:4']} ])); assert.equal(summary(b,date).fullPages,1);
b.entries.push(entry([full(1)])); assert.equal(summary(b,date).current,1);
assert.equal(summary(b,'2026-09-13').todayVolume,0);
assert.equal(countLetters('بِسْمِ ٱللَّهِ ۝ ١'),7);
assert.equal(countLetters('الم'),3);
assert.throws(()=>validate({...fresh(),past:-1}));
assert.throws(()=>validate({...fresh(),entries:[entry([full(605)])]}));
assert.throws(()=>validate({...b,entries:[b.entries[0],b.entries[0]]}));
assert.deepEqual(validate(JSON.parse(JSON.stringify(b))),b);
const data={page:1,verses:[{verse_key:'1:1',words:[{position:1,text_qpc_hafs:'بسم',page_number:1},{position:2,text_qpc_hafs:'الله',page_number:2},{position:3,char_type_name:'end',text_qpc_hafs:'١'}]}]};
assert.equal(pagePart(data).letters,3); assert.equal(pagePart(data).total,1);
assert.equal(pagePart(data,'1:1').full,false);
console.log('Reading ledger: coverage, repeats, partial pages, lifetime, undo, backup and letter counts passed.');
